name: 自动签到

on:
  # 定时触发（UTC时间，需要-8小时转换为北京时间）
  schedule:
    # 每天 00:00 UTC = 08:00 北京时间
    - cron: '0 0 * * *'

  # 手动触发
  workflow_dispatch:
    inputs:
      reason:
        description: '手动触发原因'
        required: false
        default: '测试运行'

permissions:
  contents: read

jobs:
  checkin:
    name: 执行签到
    runs-on: ubuntu-latest

    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4

      - name: 🐍 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 📦 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 执行签到脚本
        env:
          CHECKIN_TOKEN: ${{ secrets.CHECKIN_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          ACTIVITY_CODE: ${{ secrets.ACTIVITY_CODE }}
          SHOP_CODE: ${{ secrets.SHOP_CODE }}
          SCKEY: ${{ secrets.SCKEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          python checkin.py

      - name: 📋 上传执行日志
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: checkin-log-${{ github.run_number }}
          path: |
            *.log
          retention-days: 7
