name: 龙空论坛自动签到

on:
  # 定时触发
  schedule:
    - cron: '0 20 * * *'  # 北京时间 04:00
    - cron: '0 6 * * *'   # 北京时间 14:00
  
  # 手动触发
  workflow_dispatch:

# 设置GITHUB_TOKEN权限
permissions:
  contents: write  # 允许写入仓库内容

jobs:
  punch:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: 📥 检出代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
      
      # 2. 设置Python环境
      - name: 🐍 设置Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      # 3. 安装依赖
      - name: 📦 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. 显示当前时间（用于调试）
      - name: ⏰ 显示当前时间
        run: |
          echo "UTC时间: $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "北京时间: $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')"
      
      # 5. 运行签到脚本
      - name: 🚀 执行签到
        env:
          LKONG_COOKIE: ${{ secrets.LKONG_COOKIE }}
          LKONG_REQUEST_BODY: ${{ secrets.LKONG_REQUEST_BODY }}
          TZ: Asia/Shanghai
        run: |
          echo "开始执行签到任务..."
          python lkong_punch.py
      
      # 6. 提交状态文件（方案二：使用官方Action）
      - name: 💾 提交签到状态
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '📝 签到记录更新 [${{ github.run_number }}]'
          commit_user_name: Lkong Bot
          commit_user_email: bot@lkong.auto
          file_pattern: '*.txt'
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: false
        continue-on-error: true
      
      # 7. 显示运行结果
      - name: 📊 显示运行结果
        if: always()
        run: |
          echo "=========================================="
          if [ -f status.txt ]; then
            echo "📄 签到状态:"
            cat status.txt
          else
            echo "⚠️ 未找到状态文件"
          fi
          echo "=========================================="
