name: 龙空论坛自动签到

on:
  # 定时触发（使用UTC时间，北京时间-8小时）
  schedule:
    # 北京时间 04:00 = UTC 20:00 (前一天)
    - cron: '0 20 * * *'
    # 北京时间 14:00 = UTC 06:00 (当天)
    - cron: '0 6 * * *'
  
  # 手动触发（用于测试）
  workflow_dispatch:

jobs:
  punch:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: 📥 检出代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      
      # 2. 设置Python环境
      - name: 🐍 设置Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      # 3. 安装依赖
      - name: 📦 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. 运行签到脚本
      - name: 🚀 执行签到
        env:
          LKONG_COOKIE: ${{ secrets.LKONG_COOKIE }}
          LKONG_REQUEST_BODY: ${{ secrets.LKONG_REQUEST_BODY }}
          TZ: Asia/Shanghai  # 设置时区为北京时间
        run: |
          echo "当前北京时间: $(date '+%Y-%m-%d %H:%M:%S')"
          python lkong_punch.py
      
      # 5. 提交状态文件（保存签到记录）
      - name: 💾 提交签到状态
        if: always()  # 无论成功失败都执行
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update punch status - $(date '+%Y-%m-%d %H:%M:%S')" && git push)
        continue-on-error: true  # 即使提交失败也不影响任务状态
      
      # 6. 发送通知（可选，失败时通知）
      - name: 📧 发送失败通知
        if: failure()
        run: |
          echo "❌ 签到失败，请检查日志"
          # 这里可以添加其他通知方式，如邮件、Telegram等
